on:
  release:
    types: [published]
    

jobs:
  repo_matrix:
    runs-on: ubuntu-latest
    # outputs:
    #   nonprod: ${{ steps.set-env.outputs.repo }}
    steps:
      - env:
          RELEASE_ID: ${{ github.event.release.id }}
        run: echo $RELEASE_ID
