# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  on:
  pull_request:
    types:
      - closed
    paths:
      - '**.js'

jobs:
  run_if_failure:
#     if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.foo }}
        run: echo hai
